
export const doctors = [
  { id: 'doc1', name: 'Dr. Emily Carter', specialization: 'Pediatric Neurology', location: 'New York, NY', online: true, imageId: 'doctor-1', bio: 'Dr. Carter is a board-certified pediatric neurologist with over 15 years of experience specializing in developmental disorders and epilepsy. She is passionate about providing compassionate, family-centered care.' },
  { id: 'doc2', name: 'Dr. Ben Hanson', specialization: 'Developmental-Behavioral Pediatrics', location: 'Chicago, IL', online: false, imageId: 'doctor-2', bio: 'Dr. Hanson focuses on the behavioral and developmental challenges in children, including ADHD and learning disabilities. He works closely with schools and families to create comprehensive support plans.' },
  { id: 'doc3', name: 'Dr. Olivia Chen', specialization: 'Child Psychiatry', location: 'San Francisco, CA', online: true, imageId: 'doctor-3', bio: 'Dr. Chen is a child and adolescent psychiatrist who helps children and families navigate emotional and behavioral challenges. She has a special interest in anxiety and mood disorders in the context of neurodevelopmental conditions.' },
  { id: 'doc4', name: 'Dr. Aisha Khan', specialization: 'Occupational Therapy', location: 'Miami, FL', online: true, imageId: 'doctor-4', bio: 'Dr. Khan is a licensed occupational therapist who helps children develop the skills needed for daily living. Her work focuses on sensory integration, fine motor skills, and play-based therapy.' },
  { id: 'doc5', name: 'Dr. David Lee', specialization: 'Speech-Language Pathology', location: 'Austin, TX', online: false, imageId: 'doctor-5', bio: 'Dr. Lee specializes in communication disorders in children, including apraxia of speech and language delays. He utilizes a variety of techniques, including augmentative and alternative communication (AAC).' },
  { id: 'doc6', name: 'Dr. Sophia Rodriguez', specialization: 'Applied Behavior Analysis (ABA)', location: 'Los Angeles, CA', online: true, imageId: 'doctor-6', bio: 'Dr. Rodriguez is a Board Certified Behavior Analyst (BCBA-D) who designs and oversees ABA programs to help children with ASD develop new skills and reduce challenging behaviors.' },
];
